name: Pull Request
desciption: Create a pull request
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: |
        - Provide a brief summary of the changes made
        - Include any relevant issue numbers (e.g. "Fixes #123")
      validations:
        required: true
        
  - type: textarea
    id: changes-made
    attributes:
      label: Changes Made
      placeholder: |
        - List the specific changes made in the code
        - Provide context for the changes, if necessary
      validations:
        required: true

  - type: checkboxes
    id: acknowledgements
    attributes:
      label: Acknowledgements
      description: Your pull request will be closed if you haven't done these steps.
      options:
        - label: Code has been tested and works as intended
          required: true
        - label: I have written a proper description of changes made.
          required: true
