[versions]
coreKtx = "1.9.0"
desugaring = "1.1.5"
ossLicenses = "17.0.0"
annotation = "1.5.0"
legacySupport = "1.0.0"
appcompat = "1.6.0"
material = "1.8.0"
constraintlayout = "2.1.4"
apacheCommons = "3.12.0"
webkit = "1.6.0"
media = "1.6.0"
viewbinding = "7.4.1"

# SmoothRefreshLayout
srlCore = "1.7.2.4"
srlExtClassics = "1.7.2.4"
srlExtMaterial = "1.7.2.4"
srlExtDynamicRebound = "1.7.2.4"
srlExtHorizontal = "1.7.2.4"
srlExtTwoLevel = "1.7.2.4"
srlExtUtil = "1.7.2.4"

retrofit = "2.9.0"
kotlinxSerialization = "1.4.1"
kotlinxRetrofit = "0.8.0"

[libraries]
androidx-coreKtx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-annotation = { group = "androidx.annotation", name = "annotation", version.ref = "annotation" }
androidx-legacySupport = { group = "androidx.legacy", name = "legacy-support-v4", version.ref = "legacySupport" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-webkit = { group = "androidx.webkit", name = "webkit", version.ref = "webkit" }
androidx-media = { group = "androidx.media", name = "media", version.ref = "media" }
desugaring = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "desugaring" }
ossLicenses = { group = "com.google.android.gms", name = "play-services-oss-licenses", version.ref = "ossLicenses" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
apache-commons = { group = "org.apache.commons", name = "commons-lang3", version.ref = "apacheCommons" }
viewbinding = { group = "com.android.databinding", name = "viewbinding", version.ref = "viewbinding" }

# SmoothRefreshLayout
srlCore = { group = "com.github.dkzwm", name = 'srl-core', version.ref = "srlCore" }
srlExtClassics = { group = "com.github.dkzwm", name = 'srl-ext-classics', version.ref = "srlExtClassics" }
srlExtMaterial = { group = "com.github.dkzwm", name = 'srl-ext-material', version.ref = "srlExtMaterial" }
srlExtDynamicRebound = { group = "com.github.dkzwm", name = 'srl-ext-dynamic-rebound', version.ref = "srlExtDynamicRebound" }
srlExtHorizontal = { group = "com.github.dkzwm", name = 'srl-ext-horizontal', version.ref = "srlExtHorizontal" }
srlExtTwoLevel = { group = "com.github.dkzwm", name = 'srl-ext-two-level', version.ref = "srlExtTwoLevel" }
srlExtUtil = { group = "com.github.dkzwm", name = 'srl-ext-util', version.ref = "srlExtUtil" }

retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
kotlinxSerialization = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerialization" }
kotlinxRetrofit = { group = "com.jakewharton.retrofit", name = "retrofit2-kotlinx-serialization-converter", version.ref = "kotlinxRetrofit" }